# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 210d9820985eef4c57c0edd8488bcb9e74f0d3729b2de279c2e8eb1ece1b03a26fe43337f322eaa94931ba69234030c019d01b6ad02baf92988fcfce1733fe29

test:
  secret_key_base: 7cdaef9d9a3156cfe79686e13111fdf720d9d686b2c091e2548a9ca80bb4ac67c519b93e58e84234b33782044f95ad3e3f04f7ab89c4937acd15c67aab4410ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
